name: esc_pos_usb_plugin_example
description: Demonstrates how to use the esc_pos_usb_plugin plugin.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  esc_pos_usb_plugin:
    # When depending on this package from a real application you should use:
    #   esc_pos_usb_plugin: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true